### PR TITLE
Add raw binary CRM files

### PR DESCRIPTION
**Pull request by rkmaddox**
These are the CRM data as downloaded, the only change being each subdirectory was converted to a zip file for faster downloading (single, compressed file instead of thousands of individual sentences).

### CODE REVIEW

**Comment by larsoner** [comment]
Can you add some license information if you can find it?

**Comment by larsoner** [comment]
We probably should have had it for our other files. Maybe we put it in our scripts that made use of them, which is probably okay too.

**Comment by larsoner** [comment]
I'll merge this in the meantime so you can continue development with these files up, though

**Comment by rkmaddox** [comment]
There is indeed license information for the CIPIC HRTFs in the code, but it wouldn't do any harm to add it here as well. I'll do it when I get to work.

**Pull request merged**
