### PR TITLE
fix encoding errors

### PR DESCRIPTION
**Pull request by drammock**
turns out a lot of my playback difficulties were due to encoding issues in the source video.  This fixes that.  Sorry for history bloat.

### CODE REVIEW

**Comment by larsoner** [comment]
Feel free to squash and push force to keep repo smaller

**Comment by larsoner** [comment]
Or I can do it if you fear the force

**Comment by drammock** [comment]
can you do it?  I don't remember off the top how it goes, and I'm still
wrestling with pyglet's incomplete API to get other aspects working.

**Comment by larsoner** [comment]
Yeah will do in a couple hours

**Comment by larsoner** [comment]
okay, try it now it should work

**Pull request closed without merging**
